// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pizza.proto

package genproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePizzaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price         float32                `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	TypeId        int32                  `protobuf:"varint,3,opt,name=typeId,proto3" json:"typeId,omitempty"`
	Photo         string                 `protobuf:"bytes,4,opt,name=photo,proto3" json:"photo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePizzaRequest) Reset() {
	*x = CreatePizzaRequest{}
	mi := &file_pizza_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePizzaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePizzaRequest) ProtoMessage() {}

func (x *CreatePizzaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pizza_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePizzaRequest.ProtoReflect.Descriptor instead.
func (*CreatePizzaRequest) Descriptor() ([]byte, []int) {
	return file_pizza_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePizzaRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePizzaRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreatePizzaRequest) GetTypeId() int32 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

func (x *CreatePizzaRequest) GetPhoto() string {
	if x != nil {
		return x.Photo
	}
	return ""
}

type CreatePizzaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePizzaResponse) Reset() {
	*x = CreatePizzaResponse{}
	mi := &file_pizza_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePizzaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePizzaResponse) ProtoMessage() {}

func (x *CreatePizzaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pizza_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePizzaResponse.ProtoReflect.Descriptor instead.
func (*CreatePizzaResponse) Descriptor() ([]byte, []int) {
	return file_pizza_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePizzaResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetPizzasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeId        int32                  `protobuf:"varint,1,opt,name=typeId,proto3" json:"typeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPizzasRequest) Reset() {
	*x = GetPizzasRequest{}
	mi := &file_pizza_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPizzasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPizzasRequest) ProtoMessage() {}

func (x *GetPizzasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pizza_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPizzasRequest.ProtoReflect.Descriptor instead.
func (*GetPizzasRequest) Descriptor() ([]byte, []int) {
	return file_pizza_proto_rawDescGZIP(), []int{2}
}

func (x *GetPizzasRequest) GetTypeId() int32 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

type GetPizzasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pizzas        []*Pizzas              `protobuf:"bytes,1,rep,name=pizzas,proto3" json:"pizzas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPizzasResponse) Reset() {
	*x = GetPizzasResponse{}
	mi := &file_pizza_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPizzasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPizzasResponse) ProtoMessage() {}

func (x *GetPizzasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pizza_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPizzasResponse.ProtoReflect.Descriptor instead.
func (*GetPizzasResponse) Descriptor() ([]byte, []int) {
	return file_pizza_proto_rawDescGZIP(), []int{3}
}

func (x *GetPizzasResponse) GetPizzas() []*Pizzas {
	if x != nil {
		return x.Pizzas
	}
	return nil
}

type Pizzas struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price         float32                `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	Photo         string                 `protobuf:"bytes,3,opt,name=photo,proto3" json:"photo,omitempty"`
	Id            int32                  `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pizzas) Reset() {
	*x = Pizzas{}
	mi := &file_pizza_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pizzas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pizzas) ProtoMessage() {}

func (x *Pizzas) ProtoReflect() protoreflect.Message {
	mi := &file_pizza_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pizzas.ProtoReflect.Descriptor instead.
func (*Pizzas) Descriptor() ([]byte, []int) {
	return file_pizza_proto_rawDescGZIP(), []int{4}
}

func (x *Pizzas) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pizzas) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Pizzas) GetPhoto() string {
	if x != nil {
		return x.Photo
	}
	return ""
}

func (x *Pizzas) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetPizzaByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TypeId        int32                  `protobuf:"varint,2,opt,name=typeId,proto3" json:"typeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPizzaByIdRequest) Reset() {
	*x = GetPizzaByIdRequest{}
	mi := &file_pizza_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPizzaByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPizzaByIdRequest) ProtoMessage() {}

func (x *GetPizzaByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pizza_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPizzaByIdRequest.ProtoReflect.Descriptor instead.
func (*GetPizzaByIdRequest) Descriptor() ([]byte, []int) {
	return file_pizza_proto_rawDescGZIP(), []int{5}
}

func (x *GetPizzaByIdRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetPizzaByIdRequest) GetTypeId() int32 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

type GetPizzaByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price         float32                `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	Photo         string                 `protobuf:"bytes,3,opt,name=photo,proto3" json:"photo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPizzaByIdResponse) Reset() {
	*x = GetPizzaByIdResponse{}
	mi := &file_pizza_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPizzaByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPizzaByIdResponse) ProtoMessage() {}

func (x *GetPizzaByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pizza_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPizzaByIdResponse.ProtoReflect.Descriptor instead.
func (*GetPizzaByIdResponse) Descriptor() ([]byte, []int) {
	return file_pizza_proto_rawDescGZIP(), []int{6}
}

func (x *GetPizzaByIdResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetPizzaByIdResponse) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GetPizzaByIdResponse) GetPhoto() string {
	if x != nil {
		return x.Photo
	}
	return ""
}

type UpdatePizzaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TypeId        int32                  `protobuf:"varint,2,opt,name=typeId,proto3" json:"typeId,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Price         float32                `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	Photo         string                 `protobuf:"bytes,5,opt,name=photo,proto3" json:"photo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePizzaRequest) Reset() {
	*x = UpdatePizzaRequest{}
	mi := &file_pizza_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePizzaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePizzaRequest) ProtoMessage() {}

func (x *UpdatePizzaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pizza_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePizzaRequest.ProtoReflect.Descriptor instead.
func (*UpdatePizzaRequest) Descriptor() ([]byte, []int) {
	return file_pizza_proto_rawDescGZIP(), []int{7}
}

func (x *UpdatePizzaRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdatePizzaRequest) GetTypeId() int32 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

func (x *UpdatePizzaRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePizzaRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdatePizzaRequest) GetPhoto() string {
	if x != nil {
		return x.Photo
	}
	return ""
}

type UpdatePizzaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price         float32                `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePizzaResponse) Reset() {
	*x = UpdatePizzaResponse{}
	mi := &file_pizza_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePizzaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePizzaResponse) ProtoMessage() {}

func (x *UpdatePizzaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pizza_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePizzaResponse.ProtoReflect.Descriptor instead.
func (*UpdatePizzaResponse) Descriptor() ([]byte, []int) {
	return file_pizza_proto_rawDescGZIP(), []int{8}
}

func (x *UpdatePizzaResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePizzaResponse) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdatePizzaResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeletePizzaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TypeId        int32                  `protobuf:"varint,2,opt,name=typeId,proto3" json:"typeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePizzaRequest) Reset() {
	*x = DeletePizzaRequest{}
	mi := &file_pizza_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePizzaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePizzaRequest) ProtoMessage() {}

func (x *DeletePizzaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pizza_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePizzaRequest.ProtoReflect.Descriptor instead.
func (*DeletePizzaRequest) Descriptor() ([]byte, []int) {
	return file_pizza_proto_rawDescGZIP(), []int{9}
}

func (x *DeletePizzaRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeletePizzaRequest) GetTypeId() int32 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

type DeletePizzaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePizzaResponse) Reset() {
	*x = DeletePizzaResponse{}
	mi := &file_pizza_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePizzaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePizzaResponse) ProtoMessage() {}

func (x *DeletePizzaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pizza_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePizzaResponse.ProtoReflect.Descriptor instead.
func (*DeletePizzaResponse) Descriptor() ([]byte, []int) {
	return file_pizza_proto_rawDescGZIP(), []int{10}
}

func (x *DeletePizzaResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CheckIsCartExistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	IsActive      bool                   `protobuf:"varint,2,opt,name=isActive,proto3" json:"isActive,omitempty"`
	Id            int32                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckIsCartExistRequest) Reset() {
	*x = CheckIsCartExistRequest{}
	mi := &file_pizza_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIsCartExistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIsCartExistRequest) ProtoMessage() {}

func (x *CheckIsCartExistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pizza_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIsCartExistRequest.ProtoReflect.Descriptor instead.
func (*CheckIsCartExistRequest) Descriptor() ([]byte, []int) {
	return file_pizza_proto_rawDescGZIP(), []int{11}
}

func (x *CheckIsCartExistRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CheckIsCartExistRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *CheckIsCartExistRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CheckIsCartExistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	IsActive      bool                   `protobuf:"varint,2,opt,name=isActive,proto3" json:"isActive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckIsCartExistResponse) Reset() {
	*x = CheckIsCartExistResponse{}
	mi := &file_pizza_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIsCartExistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIsCartExistResponse) ProtoMessage() {}

func (x *CheckIsCartExistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pizza_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIsCartExistResponse.ProtoReflect.Descriptor instead.
func (*CheckIsCartExistResponse) Descriptor() ([]byte, []int) {
	return file_pizza_proto_rawDescGZIP(), []int{12}
}

func (x *CheckIsCartExistResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CheckIsCartExistResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type CartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	IsActive      bool                   `protobuf:"varint,3,opt,name=isActive,proto3" json:"isActive,omitempty"`
	TotalCost     float32                `protobuf:"fixed32,4,opt,name=totalCost,proto3" json:"totalCost,omitempty"`
	CartItemId    int32                  `protobuf:"varint,5,opt,name=cartItemId,proto3" json:"cartItemId,omitempty"`
	PizzaId       int32                  `protobuf:"varint,6,opt,name=pizzaId,proto3" json:"pizzaId,omitempty"`
	PizzaTypeId   int32                  `protobuf:"varint,7,opt,name=pizzaTypeId,proto3" json:"pizzaTypeId,omitempty"`
	Cost          float32                `protobuf:"fixed32,8,opt,name=cost,proto3" json:"cost,omitempty"`
	Quantity      int32                  `protobuf:"varint,9,opt,name=quantity,proto3" json:"quantity,omitempty"`
	CartId        int32                  `protobuf:"varint,10,opt,name=cartId,proto3" json:"cartId,omitempty"`
	Items         []*CartItems           `protobuf:"bytes,11,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartRequest) Reset() {
	*x = CartRequest{}
	mi := &file_pizza_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartRequest) ProtoMessage() {}

func (x *CartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pizza_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartRequest.ProtoReflect.Descriptor instead.
func (*CartRequest) Descriptor() ([]byte, []int) {
	return file_pizza_proto_rawDescGZIP(), []int{13}
}

func (x *CartRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CartRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CartRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *CartRequest) GetTotalCost() float32 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

func (x *CartRequest) GetCartItemId() int32 {
	if x != nil {
		return x.CartItemId
	}
	return 0
}

func (x *CartRequest) GetPizzaId() int32 {
	if x != nil {
		return x.PizzaId
	}
	return 0
}

func (x *CartRequest) GetPizzaTypeId() int32 {
	if x != nil {
		return x.PizzaTypeId
	}
	return 0
}

func (x *CartRequest) GetCost() float32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *CartRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CartRequest) GetCartId() int32 {
	if x != nil {
		return x.CartId
	}
	return 0
}

func (x *CartRequest) GetItems() []*CartItems {
	if x != nil {
		return x.Items
	}
	return nil
}

type CartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartResponse) Reset() {
	*x = CartResponse{}
	mi := &file_pizza_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartResponse) ProtoMessage() {}

func (x *CartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pizza_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartResponse.ProtoReflect.Descriptor instead.
func (*CartResponse) Descriptor() ([]byte, []int) {
	return file_pizza_proto_rawDescGZIP(), []int{14}
}

func (x *CartResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CartItems struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCost     float32                `protobuf:"fixed32,1,opt,name=totalCost,proto3" json:"totalCost,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	PizzaId       int32                  `protobuf:"varint,3,opt,name=pizzaId,proto3" json:"pizzaId,omitempty"`
	PizzaTypeId   int32                  `protobuf:"varint,4,opt,name=pizzaTypeId,proto3" json:"pizzaTypeId,omitempty"`
	Cost          float32                `protobuf:"fixed32,5,opt,name=cost,proto3" json:"cost,omitempty"`
	Quantity      int32                  `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	CartId        int32                  `protobuf:"varint,7,opt,name=cartId,proto3" json:"cartId,omitempty"`
	UserId        int32                  `protobuf:"varint,8,opt,name=userId,proto3" json:"userId,omitempty"`
	Items         []*CartItems           `protobuf:"bytes,9,rep,name=items,proto3" json:"items,omitempty"`
	Name          string                 `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	Photo         string                 `protobuf:"bytes,11,opt,name=photo,proto3" json:"photo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItems) Reset() {
	*x = CartItems{}
	mi := &file_pizza_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItems) ProtoMessage() {}

func (x *CartItems) ProtoReflect() protoreflect.Message {
	mi := &file_pizza_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItems.ProtoReflect.Descriptor instead.
func (*CartItems) Descriptor() ([]byte, []int) {
	return file_pizza_proto_rawDescGZIP(), []int{15}
}

func (x *CartItems) GetTotalCost() float32 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

func (x *CartItems) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CartItems) GetPizzaId() int32 {
	if x != nil {
		return x.PizzaId
	}
	return 0
}

func (x *CartItems) GetPizzaTypeId() int32 {
	if x != nil {
		return x.PizzaTypeId
	}
	return 0
}

func (x *CartItems) GetCost() float32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *CartItems) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CartItems) GetCartId() int32 {
	if x != nil {
		return x.CartId
	}
	return 0
}

func (x *CartItems) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CartItems) GetItems() []*CartItems {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CartItems) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CartItems) GetPhoto() string {
	if x != nil {
		return x.Photo
	}
	return ""
}

type CartItemsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CartId        int32                  `protobuf:"varint,3,opt,name=cartId,proto3" json:"cartId,omitempty"`
	PizzaId       int32                  `protobuf:"varint,4,opt,name=pizzaId,proto3" json:"pizzaId,omitempty"`
	Cost          float32                `protobuf:"fixed32,5,opt,name=cost,proto3" json:"cost,omitempty"`
	Quantity      int32                  `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	PizzaTypeId   int32                  `protobuf:"varint,7,opt,name=pizzaTypeId,proto3" json:"pizzaTypeId,omitempty"`
	TotalCost     float32                `protobuf:"fixed32,8,opt,name=totalCost,proto3" json:"totalCost,omitempty"`
	CartItems     []*CartItems           `protobuf:"bytes,9,rep,name=cartItems,proto3" json:"cartItems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItemsResp) Reset() {
	*x = CartItemsResp{}
	mi := &file_pizza_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItemsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItemsResp) ProtoMessage() {}

func (x *CartItemsResp) ProtoReflect() protoreflect.Message {
	mi := &file_pizza_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItemsResp.ProtoReflect.Descriptor instead.
func (*CartItemsResp) Descriptor() ([]byte, []int) {
	return file_pizza_proto_rawDescGZIP(), []int{16}
}

func (x *CartItemsResp) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CartItemsResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CartItemsResp) GetCartId() int32 {
	if x != nil {
		return x.CartId
	}
	return 0
}

func (x *CartItemsResp) GetPizzaId() int32 {
	if x != nil {
		return x.PizzaId
	}
	return 0
}

func (x *CartItemsResp) GetCost() float32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *CartItemsResp) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CartItemsResp) GetPizzaTypeId() int32 {
	if x != nil {
		return x.PizzaTypeId
	}
	return 0
}

func (x *CartItemsResp) GetTotalCost() float32 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

func (x *CartItemsResp) GetCartItems() []*CartItems {
	if x != nil {
		return x.CartItems
	}
	return nil
}

type GetCartHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	OrderId       int32                  `protobuf:"varint,2,opt,name=orderId,proto3" json:"orderId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartHistoryRequest) Reset() {
	*x = GetCartHistoryRequest{}
	mi := &file_pizza_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartHistoryRequest) ProtoMessage() {}

func (x *GetCartHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pizza_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetCartHistoryRequest) Descriptor() ([]byte, []int) {
	return file_pizza_proto_rawDescGZIP(), []int{17}
}

func (x *GetCartHistoryRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetCartHistoryRequest) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type GetCartHistoryResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	CartId        int32                     `protobuf:"varint,1,opt,name=cartId,proto3" json:"cartId,omitempty"`
	Date          *timestamppb.Timestamp    `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	UserId        int32                     `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	IsActive      bool                      `protobuf:"varint,4,opt,name=isActive,proto3" json:"isActive,omitempty"`
	CartHistory   []*GetCartHistoryResponse `protobuf:"bytes,5,rep,name=cartHistory,proto3" json:"cartHistory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartHistoryResponse) Reset() {
	*x = GetCartHistoryResponse{}
	mi := &file_pizza_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartHistoryResponse) ProtoMessage() {}

func (x *GetCartHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pizza_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetCartHistoryResponse) Descriptor() ([]byte, []int) {
	return file_pizza_proto_rawDescGZIP(), []int{18}
}

func (x *GetCartHistoryResponse) GetCartId() int32 {
	if x != nil {
		return x.CartId
	}
	return 0
}

func (x *GetCartHistoryResponse) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *GetCartHistoryResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetCartHistoryResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *GetCartHistoryResponse) GetCartHistory() []*GetCartHistoryResponse {
	if x != nil {
		return x.CartHistory
	}
	return nil
}

type GetCartItemHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int32                  `protobuf:"varint,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartItemHistoryRequest) Reset() {
	*x = GetCartItemHistoryRequest{}
	mi := &file_pizza_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartItemHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartItemHistoryRequest) ProtoMessage() {}

func (x *GetCartItemHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pizza_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartItemHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetCartItemHistoryRequest) Descriptor() ([]byte, []int) {
	return file_pizza_proto_rawDescGZIP(), []int{19}
}

func (x *GetCartItemHistoryRequest) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type GetCartItemHistoryResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	CartHistoryId int32                         `protobuf:"varint,1,opt,name=cartHistoryId,proto3" json:"cartHistoryId,omitempty"`
	PizzaId       int32                         `protobuf:"varint,2,opt,name=pizzaId,proto3" json:"pizzaId,omitempty"`
	PizzaTypeId   int32                         `protobuf:"varint,3,opt,name=pizzaTypeId,proto3" json:"pizzaTypeId,omitempty"`
	Cost          float32                       `protobuf:"fixed32,4,opt,name=cost,proto3" json:"cost,omitempty"`
	Quantity      int32                         `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	CartHistory   []*GetCartItemHistoryResponse `protobuf:"bytes,6,rep,name=cartHistory,proto3" json:"cartHistory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartItemHistoryResponse) Reset() {
	*x = GetCartItemHistoryResponse{}
	mi := &file_pizza_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartItemHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartItemHistoryResponse) ProtoMessage() {}

func (x *GetCartItemHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pizza_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartItemHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetCartItemHistoryResponse) Descriptor() ([]byte, []int) {
	return file_pizza_proto_rawDescGZIP(), []int{20}
}

func (x *GetCartItemHistoryResponse) GetCartHistoryId() int32 {
	if x != nil {
		return x.CartHistoryId
	}
	return 0
}

func (x *GetCartItemHistoryResponse) GetPizzaId() int32 {
	if x != nil {
		return x.PizzaId
	}
	return 0
}

func (x *GetCartItemHistoryResponse) GetPizzaTypeId() int32 {
	if x != nil {
		return x.PizzaTypeId
	}
	return 0
}

func (x *GetCartItemHistoryResponse) GetCost() float32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *GetCartItemHistoryResponse) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *GetCartItemHistoryResponse) GetCartHistory() []*GetCartItemHistoryResponse {
	if x != nil {
		return x.CartHistory
	}
	return nil
}

type CheckIsOrderedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	IsOrdered     bool                   `protobuf:"varint,2,opt,name=isOrdered,proto3" json:"isOrdered,omitempty"`
	Id            int32                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckIsOrderedRequest) Reset() {
	*x = CheckIsOrderedRequest{}
	mi := &file_pizza_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIsOrderedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIsOrderedRequest) ProtoMessage() {}

func (x *CheckIsOrderedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pizza_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIsOrderedRequest.ProtoReflect.Descriptor instead.
func (*CheckIsOrderedRequest) Descriptor() ([]byte, []int) {
	return file_pizza_proto_rawDescGZIP(), []int{21}
}

func (x *CheckIsOrderedRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CheckIsOrderedRequest) GetIsOrdered() bool {
	if x != nil {
		return x.IsOrdered
	}
	return false
}

func (x *CheckIsOrderedRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CheckIsOrderedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	IsOrdered     bool                   `protobuf:"varint,2,opt,name=isOrdered,proto3" json:"isOrdered,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckIsOrderedResponse) Reset() {
	*x = CheckIsOrderedResponse{}
	mi := &file_pizza_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIsOrderedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIsOrderedResponse) ProtoMessage() {}

func (x *CheckIsOrderedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pizza_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIsOrderedResponse.ProtoReflect.Descriptor instead.
func (*CheckIsOrderedResponse) Descriptor() ([]byte, []int) {
	return file_pizza_proto_rawDescGZIP(), []int{22}
}

func (x *CheckIsOrderedResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CheckIsOrderedResponse) GetIsOrdered() bool {
	if x != nil {
		return x.IsOrdered
	}
	return false
}

func (x *CheckIsOrderedResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type OrderItemData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PizzaId       int32                  `protobuf:"varint,1,opt,name=pizzaId,proto3" json:"pizzaId,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	ItemIds       []int32                `protobuf:"varint,3,rep,packed,name=itemIds,proto3" json:"itemIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItemData) Reset() {
	*x = OrderItemData{}
	mi := &file_pizza_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemData) ProtoMessage() {}

func (x *OrderItemData) ProtoReflect() protoreflect.Message {
	mi := &file_pizza_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemData.ProtoReflect.Descriptor instead.
func (*OrderItemData) Descriptor() ([]byte, []int) {
	return file_pizza_proto_rawDescGZIP(), []int{23}
}

func (x *OrderItemData) GetPizzaId() int32 {
	if x != nil {
		return x.PizzaId
	}
	return 0
}

func (x *OrderItemData) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItemData) GetItemIds() []int32 {
	if x != nil {
		return x.ItemIds
	}
	return nil
}

type OrderPizzaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	IsOrdered     bool                   `protobuf:"varint,3,opt,name=isOrdered,proto3" json:"isOrdered,omitempty"`
	UserId        int32                  `protobuf:"varint,4,opt,name=userId,proto3" json:"userId,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	ItemIds       []int32                `protobuf:"varint,6,rep,packed,name=itemIds,proto3" json:"itemIds,omitempty"`
	PizzaId       int32                  `protobuf:"varint,7,opt,name=pizza_id,json=pizzaId,proto3" json:"pizza_id,omitempty"`
	Cost          []float32              `protobuf:"fixed32,8,rep,packed,name=cost,proto3" json:"cost,omitempty"`
	CartId        int32                  `protobuf:"varint,9,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,10,opt,name=quantity,proto3" json:"quantity,omitempty"`
	IsExist       bool                   `protobuf:"varint,11,opt,name=isExist,proto3" json:"isExist,omitempty"`
	Limit         int32                  `protobuf:"varint,12,opt,name=limit,proto3" json:"limit,omitempty"`
	Items         []*OrderItemData       `protobuf:"bytes,13,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderPizzaRequest) Reset() {
	*x = OrderPizzaRequest{}
	mi := &file_pizza_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderPizzaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPizzaRequest) ProtoMessage() {}

func (x *OrderPizzaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pizza_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPizzaRequest.ProtoReflect.Descriptor instead.
func (*OrderPizzaRequest) Descriptor() ([]byte, []int) {
	return file_pizza_proto_rawDescGZIP(), []int{24}
}

func (x *OrderPizzaRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderPizzaRequest) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *OrderPizzaRequest) GetIsOrdered() bool {
	if x != nil {
		return x.IsOrdered
	}
	return false
}

func (x *OrderPizzaRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderPizzaRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderPizzaRequest) GetItemIds() []int32 {
	if x != nil {
		return x.ItemIds
	}
	return nil
}

func (x *OrderPizzaRequest) GetPizzaId() int32 {
	if x != nil {
		return x.PizzaId
	}
	return 0
}

func (x *OrderPizzaRequest) GetCost() []float32 {
	if x != nil {
		return x.Cost
	}
	return nil
}

func (x *OrderPizzaRequest) GetCartId() int32 {
	if x != nil {
		return x.CartId
	}
	return 0
}

func (x *OrderPizzaRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderPizzaRequest) GetIsExist() bool {
	if x != nil {
		return x.IsExist
	}
	return false
}

func (x *OrderPizzaRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *OrderPizzaRequest) GetItems() []*OrderItemData {
	if x != nil {
		return x.Items
	}
	return nil
}

type OrderPizzaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Id            int32                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	ItemIds       []int32                `protobuf:"varint,4,rep,packed,name=itemIds,proto3" json:"itemIds,omitempty"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	IsExist       bool                   `protobuf:"varint,6,opt,name=isExist,proto3" json:"isExist,omitempty"`
	Cost          []float32              `protobuf:"fixed32,7,rep,packed,name=cost,proto3" json:"cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderPizzaResponse) Reset() {
	*x = OrderPizzaResponse{}
	mi := &file_pizza_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderPizzaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPizzaResponse) ProtoMessage() {}

func (x *OrderPizzaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pizza_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPizzaResponse.ProtoReflect.Descriptor instead.
func (*OrderPizzaResponse) Descriptor() ([]byte, []int) {
	return file_pizza_proto_rawDescGZIP(), []int{25}
}

func (x *OrderPizzaResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *OrderPizzaResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderPizzaResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderPizzaResponse) GetItemIds() []int32 {
	if x != nil {
		return x.ItemIds
	}
	return nil
}

func (x *OrderPizzaResponse) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *OrderPizzaResponse) GetIsExist() bool {
	if x != nil {
		return x.IsExist
	}
	return false
}

func (x *OrderPizzaResponse) GetCost() []float32 {
	if x != nil {
		return x.Cost
	}
	return nil
}

var File_pizza_proto protoreflect.FileDescriptor

const file_pizza_proto_rawDesc = "" +
	"\n" +
	"\vpizza.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"l\n" +
	"\x12CreatePizzaRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x02R\x05price\x12\x16\n" +
	"\x06typeId\x18\x03 \x01(\x05R\x06typeId\x12\x14\n" +
	"\x05photo\x18\x04 \x01(\tR\x05photo\"/\n" +
	"\x13CreatePizzaResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"*\n" +
	"\x10GetPizzasRequest\x12\x16\n" +
	"\x06typeId\x18\x01 \x01(\x05R\x06typeId\":\n" +
	"\x11GetPizzasResponse\x12%\n" +
	"\x06pizzas\x18\x01 \x03(\v2\r.proto.PizzasR\x06pizzas\"X\n" +
	"\x06Pizzas\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x02R\x05price\x12\x14\n" +
	"\x05photo\x18\x03 \x01(\tR\x05photo\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\x05R\x02id\"=\n" +
	"\x13GetPizzaByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06typeId\x18\x02 \x01(\x05R\x06typeId\"V\n" +
	"\x14GetPizzaByIdResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x02R\x05price\x12\x14\n" +
	"\x05photo\x18\x03 \x01(\tR\x05photo\"|\n" +
	"\x12UpdatePizzaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06typeId\x18\x02 \x01(\x05R\x06typeId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x02R\x05price\x12\x14\n" +
	"\x05photo\x18\x05 \x01(\tR\x05photo\"Y\n" +
	"\x13UpdatePizzaResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x02R\x05price\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"<\n" +
	"\x12DeletePizzaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06typeId\x18\x02 \x01(\x05R\x06typeId\"/\n" +
	"\x13DeletePizzaResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"]\n" +
	"\x17CheckIsCartExistRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x05R\x06userId\x12\x1a\n" +
	"\bisActive\x18\x02 \x01(\bR\bisActive\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x05R\x02id\"P\n" +
	"\x18CheckIsCartExistResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1a\n" +
	"\bisActive\x18\x02 \x01(\bR\bisActive\"\xbb\x02\n" +
	"\vCartRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x05R\x06userId\x12\x1a\n" +
	"\bisActive\x18\x03 \x01(\bR\bisActive\x12\x1c\n" +
	"\ttotalCost\x18\x04 \x01(\x02R\ttotalCost\x12\x1e\n" +
	"\n" +
	"cartItemId\x18\x05 \x01(\x05R\n" +
	"cartItemId\x12\x18\n" +
	"\apizzaId\x18\x06 \x01(\x05R\apizzaId\x12 \n" +
	"\vpizzaTypeId\x18\a \x01(\x05R\vpizzaTypeId\x12\x12\n" +
	"\x04cost\x18\b \x01(\x02R\x04cost\x12\x1a\n" +
	"\bquantity\x18\t \x01(\x05R\bquantity\x12\x16\n" +
	"\x06cartId\x18\n" +
	" \x01(\x05R\x06cartId\x12&\n" +
	"\x05items\x18\v \x03(\v2\x10.proto.CartItemsR\x05items\"(\n" +
	"\fCartResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xa7\x02\n" +
	"\tCartItems\x12\x1c\n" +
	"\ttotalCost\x18\x01 \x01(\x02R\ttotalCost\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12\x18\n" +
	"\apizzaId\x18\x03 \x01(\x05R\apizzaId\x12 \n" +
	"\vpizzaTypeId\x18\x04 \x01(\x05R\vpizzaTypeId\x12\x12\n" +
	"\x04cost\x18\x05 \x01(\x02R\x04cost\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x05R\bquantity\x12\x16\n" +
	"\x06cartId\x18\a \x01(\x05R\x06cartId\x12\x16\n" +
	"\x06userId\x18\b \x01(\x05R\x06userId\x12&\n" +
	"\x05items\x18\t \x03(\v2\x10.proto.CartItemsR\x05items\x12\x12\n" +
	"\x04name\x18\n" +
	" \x01(\tR\x04name\x12\x14\n" +
	"\x05photo\x18\v \x01(\tR\x05photo\"\x8b\x02\n" +
	"\rCartItemsResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06cartId\x18\x03 \x01(\x05R\x06cartId\x12\x18\n" +
	"\apizzaId\x18\x04 \x01(\x05R\apizzaId\x12\x12\n" +
	"\x04cost\x18\x05 \x01(\x02R\x04cost\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x05R\bquantity\x12 \n" +
	"\vpizzaTypeId\x18\a \x01(\x05R\vpizzaTypeId\x12\x1c\n" +
	"\ttotalCost\x18\b \x01(\x02R\ttotalCost\x12.\n" +
	"\tcartItems\x18\t \x03(\v2\x10.proto.CartItemsR\tcartItems\"I\n" +
	"\x15GetCartHistoryRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x05R\x06userId\x12\x18\n" +
	"\aorderId\x18\x02 \x01(\x05R\aorderId\"\xd5\x01\n" +
	"\x16GetCartHistoryResponse\x12\x16\n" +
	"\x06cartId\x18\x01 \x01(\x05R\x06cartId\x12.\n" +
	"\x04date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\x05R\x06userId\x12\x1a\n" +
	"\bisActive\x18\x04 \x01(\bR\bisActive\x12?\n" +
	"\vcartHistory\x18\x05 \x03(\v2\x1d.proto.GetCartHistoryResponseR\vcartHistory\"5\n" +
	"\x19GetCartItemHistoryRequest\x12\x18\n" +
	"\aorderId\x18\x01 \x01(\x05R\aorderId\"\xf3\x01\n" +
	"\x1aGetCartItemHistoryResponse\x12$\n" +
	"\rcartHistoryId\x18\x01 \x01(\x05R\rcartHistoryId\x12\x18\n" +
	"\apizzaId\x18\x02 \x01(\x05R\apizzaId\x12 \n" +
	"\vpizzaTypeId\x18\x03 \x01(\x05R\vpizzaTypeId\x12\x12\n" +
	"\x04cost\x18\x04 \x01(\x02R\x04cost\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x05R\bquantity\x12C\n" +
	"\vcartHistory\x18\x06 \x03(\v2!.proto.GetCartItemHistoryResponseR\vcartHistory\"]\n" +
	"\x15CheckIsOrderedRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x05R\x06userId\x12\x1c\n" +
	"\tisOrdered\x18\x02 \x01(\bR\tisOrdered\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x05R\x02id\"h\n" +
	"\x16CheckIsOrderedResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1c\n" +
	"\tisOrdered\x18\x02 \x01(\bR\tisOrdered\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"_\n" +
	"\rOrderItemData\x12\x18\n" +
	"\apizzaId\x18\x01 \x01(\x05R\apizzaId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12\x18\n" +
	"\aitemIds\x18\x03 \x03(\x05R\aitemIds\"\xfb\x02\n" +
	"\x11OrderPizzaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12.\n" +
	"\x04date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12\x1c\n" +
	"\tisOrdered\x18\x03 \x01(\bR\tisOrdered\x12\x16\n" +
	"\x06userId\x18\x04 \x01(\x05R\x06userId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x18\n" +
	"\aitemIds\x18\x06 \x03(\x05R\aitemIds\x12\x19\n" +
	"\bpizza_id\x18\a \x01(\x05R\apizzaId\x12\x12\n" +
	"\x04cost\x18\b \x03(\x02R\x04cost\x12\x17\n" +
	"\acart_id\x18\t \x01(\x05R\x06cartId\x12\x1a\n" +
	"\bquantity\x18\n" +
	" \x01(\x05R\bquantity\x12\x18\n" +
	"\aisExist\x18\v \x01(\bR\aisExist\x12\x14\n" +
	"\x05limit\x18\f \x01(\x05R\x05limit\x12*\n" +
	"\x05items\x18\r \x03(\v2\x14.proto.OrderItemDataR\x05items\"\xce\x01\n" +
	"\x12OrderPizzaResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x05R\x02id\x12\x18\n" +
	"\aitemIds\x18\x04 \x03(\x05R\aitemIds\x12.\n" +
	"\x04date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12\x18\n" +
	"\aisExist\x18\x06 \x01(\bR\aisExist\x12\x12\n" +
	"\x04cost\x18\a \x03(\x02R\x04cost2\xeb\x03\n" +
	"\fPizzaService\x12D\n" +
	"\vCreatePizza\x12\x19.proto.CreatePizzaRequest\x1a\x1a.proto.CreatePizzaResponse\x12H\n" +
	"\x0fCreatePizzaType\x12\x19.proto.CreatePizzaRequest\x1a\x1a.proto.CreatePizzaResponse\x12>\n" +
	"\tGetPizzas\x12\x17.proto.GetPizzasRequest\x1a\x18.proto.GetPizzasResponse\x12G\n" +
	"\fGetPizzaById\x12\x1a.proto.GetPizzaByIdRequest\x1a\x1b.proto.GetPizzaByIdResponse\x12D\n" +
	"\vUpdatePizza\x12\x19.proto.UpdatePizzaRequest\x1a\x1a.proto.UpdatePizzaResponse\x12D\n" +
	"\vDeletePizza\x12\x19.proto.DeletePizzaRequest\x1a\x1a.proto.DeletePizzaResponse\x126\n" +
	"\fGetPizzaCost\x12\x10.proto.CartItems\x1a\x14.proto.CartItemsResp2\x8c\x04\n" +
	"\vCartService\x12/\n" +
	"\x04Cart\x12\x12.proto.CartRequest\x1a\x13.proto.CartResponse\x12?\n" +
	"\x15DecreasePizzaQuantity\x12\x10.proto.CartItems\x1a\x14.proto.CartItemsResp\x126\n" +
	"\fGetTotalCost\x12\x10.proto.CartItems\x1a\x14.proto.CartItemsResp\x12M\n" +
	"\x0eGetCartHistory\x12\x1c.proto.GetCartHistoryRequest\x1a\x1d.proto.GetCartHistoryResponse\x12Y\n" +
	"\x12GetCartItemHistory\x12 .proto.GetCartItemHistoryRequest\x1a!.proto.GetCartItemHistoryResponse\x125\n" +
	"\vGetFromCart\x12\x10.proto.CartItems\x1a\x14.proto.CartItemsResp\x126\n" +
	"\fClearTheCart\x12\x10.proto.CartItems\x1a\x14.proto.CartItemsResp\x12:\n" +
	"\x10ClearTheCartById\x12\x10.proto.CartItems\x1a\x14.proto.CartItemsResp2\xa0\x01\n" +
	"\fOrderService\x12M\n" +
	"\x0eCheckIsOrdered\x12\x1c.proto.CheckIsOrderedRequest\x1a\x1d.proto.CheckIsOrderedResponse\x12A\n" +
	"\n" +
	"OrderPizza\x12\x18.proto.OrderPizzaRequest\x1a\x19.proto.OrderPizzaResponseB\vZ\tgenproto/b\x06proto3"

var (
	file_pizza_proto_rawDescOnce sync.Once
	file_pizza_proto_rawDescData []byte
)

func file_pizza_proto_rawDescGZIP() []byte {
	file_pizza_proto_rawDescOnce.Do(func() {
		file_pizza_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pizza_proto_rawDesc), len(file_pizza_proto_rawDesc)))
	})
	return file_pizza_proto_rawDescData
}

var file_pizza_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_pizza_proto_goTypes = []any{
	(*CreatePizzaRequest)(nil),         // 0: proto.CreatePizzaRequest
	(*CreatePizzaResponse)(nil),        // 1: proto.CreatePizzaResponse
	(*GetPizzasRequest)(nil),           // 2: proto.GetPizzasRequest
	(*GetPizzasResponse)(nil),          // 3: proto.GetPizzasResponse
	(*Pizzas)(nil),                     // 4: proto.Pizzas
	(*GetPizzaByIdRequest)(nil),        // 5: proto.GetPizzaByIdRequest
	(*GetPizzaByIdResponse)(nil),       // 6: proto.GetPizzaByIdResponse
	(*UpdatePizzaRequest)(nil),         // 7: proto.UpdatePizzaRequest
	(*UpdatePizzaResponse)(nil),        // 8: proto.UpdatePizzaResponse
	(*DeletePizzaRequest)(nil),         // 9: proto.DeletePizzaRequest
	(*DeletePizzaResponse)(nil),        // 10: proto.DeletePizzaResponse
	(*CheckIsCartExistRequest)(nil),    // 11: proto.CheckIsCartExistRequest
	(*CheckIsCartExistResponse)(nil),   // 12: proto.CheckIsCartExistResponse
	(*CartRequest)(nil),                // 13: proto.CartRequest
	(*CartResponse)(nil),               // 14: proto.CartResponse
	(*CartItems)(nil),                  // 15: proto.CartItems
	(*CartItemsResp)(nil),              // 16: proto.CartItemsResp
	(*GetCartHistoryRequest)(nil),      // 17: proto.GetCartHistoryRequest
	(*GetCartHistoryResponse)(nil),     // 18: proto.GetCartHistoryResponse
	(*GetCartItemHistoryRequest)(nil),  // 19: proto.GetCartItemHistoryRequest
	(*GetCartItemHistoryResponse)(nil), // 20: proto.GetCartItemHistoryResponse
	(*CheckIsOrderedRequest)(nil),      // 21: proto.CheckIsOrderedRequest
	(*CheckIsOrderedResponse)(nil),     // 22: proto.CheckIsOrderedResponse
	(*OrderItemData)(nil),              // 23: proto.OrderItemData
	(*OrderPizzaRequest)(nil),          // 24: proto.OrderPizzaRequest
	(*OrderPizzaResponse)(nil),         // 25: proto.OrderPizzaResponse
	(*timestamppb.Timestamp)(nil),      // 26: google.protobuf.Timestamp
}
var file_pizza_proto_depIdxs = []int32{
	4,  // 0: proto.GetPizzasResponse.pizzas:type_name -> proto.Pizzas
	15, // 1: proto.CartRequest.items:type_name -> proto.CartItems
	15, // 2: proto.CartItems.items:type_name -> proto.CartItems
	15, // 3: proto.CartItemsResp.cartItems:type_name -> proto.CartItems
	26, // 4: proto.GetCartHistoryResponse.date:type_name -> google.protobuf.Timestamp
	18, // 5: proto.GetCartHistoryResponse.cartHistory:type_name -> proto.GetCartHistoryResponse
	20, // 6: proto.GetCartItemHistoryResponse.cartHistory:type_name -> proto.GetCartItemHistoryResponse
	26, // 7: proto.OrderPizzaRequest.date:type_name -> google.protobuf.Timestamp
	23, // 8: proto.OrderPizzaRequest.items:type_name -> proto.OrderItemData
	26, // 9: proto.OrderPizzaResponse.date:type_name -> google.protobuf.Timestamp
	0,  // 10: proto.PizzaService.CreatePizza:input_type -> proto.CreatePizzaRequest
	0,  // 11: proto.PizzaService.CreatePizzaType:input_type -> proto.CreatePizzaRequest
	2,  // 12: proto.PizzaService.GetPizzas:input_type -> proto.GetPizzasRequest
	5,  // 13: proto.PizzaService.GetPizzaById:input_type -> proto.GetPizzaByIdRequest
	7,  // 14: proto.PizzaService.UpdatePizza:input_type -> proto.UpdatePizzaRequest
	9,  // 15: proto.PizzaService.DeletePizza:input_type -> proto.DeletePizzaRequest
	15, // 16: proto.PizzaService.GetPizzaCost:input_type -> proto.CartItems
	13, // 17: proto.CartService.Cart:input_type -> proto.CartRequest
	15, // 18: proto.CartService.DecreasePizzaQuantity:input_type -> proto.CartItems
	15, // 19: proto.CartService.GetTotalCost:input_type -> proto.CartItems
	17, // 20: proto.CartService.GetCartHistory:input_type -> proto.GetCartHistoryRequest
	19, // 21: proto.CartService.GetCartItemHistory:input_type -> proto.GetCartItemHistoryRequest
	15, // 22: proto.CartService.GetFromCart:input_type -> proto.CartItems
	15, // 23: proto.CartService.ClearTheCart:input_type -> proto.CartItems
	15, // 24: proto.CartService.ClearTheCartById:input_type -> proto.CartItems
	21, // 25: proto.OrderService.CheckIsOrdered:input_type -> proto.CheckIsOrderedRequest
	24, // 26: proto.OrderService.OrderPizza:input_type -> proto.OrderPizzaRequest
	1,  // 27: proto.PizzaService.CreatePizza:output_type -> proto.CreatePizzaResponse
	1,  // 28: proto.PizzaService.CreatePizzaType:output_type -> proto.CreatePizzaResponse
	3,  // 29: proto.PizzaService.GetPizzas:output_type -> proto.GetPizzasResponse
	6,  // 30: proto.PizzaService.GetPizzaById:output_type -> proto.GetPizzaByIdResponse
	8,  // 31: proto.PizzaService.UpdatePizza:output_type -> proto.UpdatePizzaResponse
	10, // 32: proto.PizzaService.DeletePizza:output_type -> proto.DeletePizzaResponse
	16, // 33: proto.PizzaService.GetPizzaCost:output_type -> proto.CartItemsResp
	14, // 34: proto.CartService.Cart:output_type -> proto.CartResponse
	16, // 35: proto.CartService.DecreasePizzaQuantity:output_type -> proto.CartItemsResp
	16, // 36: proto.CartService.GetTotalCost:output_type -> proto.CartItemsResp
	18, // 37: proto.CartService.GetCartHistory:output_type -> proto.GetCartHistoryResponse
	20, // 38: proto.CartService.GetCartItemHistory:output_type -> proto.GetCartItemHistoryResponse
	16, // 39: proto.CartService.GetFromCart:output_type -> proto.CartItemsResp
	16, // 40: proto.CartService.ClearTheCart:output_type -> proto.CartItemsResp
	16, // 41: proto.CartService.ClearTheCartById:output_type -> proto.CartItemsResp
	22, // 42: proto.OrderService.CheckIsOrdered:output_type -> proto.CheckIsOrderedResponse
	25, // 43: proto.OrderService.OrderPizza:output_type -> proto.OrderPizzaResponse
	27, // [27:44] is the sub-list for method output_type
	10, // [10:27] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_pizza_proto_init() }
func file_pizza_proto_init() {
	if File_pizza_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pizza_proto_rawDesc), len(file_pizza_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_pizza_proto_goTypes,
		DependencyIndexes: file_pizza_proto_depIdxs,
		MessageInfos:      file_pizza_proto_msgTypes,
	}.Build()
	File_pizza_proto = out.File
	file_pizza_proto_goTypes = nil
	file_pizza_proto_depIdxs = nil
}
