// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: pizza.proto

package genproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PizzaService_CreatePizza_FullMethodName     = "/proto.PizzaService/CreatePizza"
	PizzaService_CreatePizzaType_FullMethodName = "/proto.PizzaService/CreatePizzaType"
	PizzaService_GetPizzas_FullMethodName       = "/proto.PizzaService/GetPizzas"
	PizzaService_GetPizzaById_FullMethodName    = "/proto.PizzaService/GetPizzaById"
	PizzaService_UpdatePizza_FullMethodName     = "/proto.PizzaService/UpdatePizza"
	PizzaService_DeletePizza_FullMethodName     = "/proto.PizzaService/DeletePizza"
	PizzaService_GetPizzaCost_FullMethodName    = "/proto.PizzaService/GetPizzaCost"
)

// PizzaServiceClient is the client API for PizzaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PizzaServiceClient interface {
	CreatePizza(ctx context.Context, in *CreatePizzaRequest, opts ...grpc.CallOption) (*CreatePizzaResponse, error)
	CreatePizzaType(ctx context.Context, in *CreatePizzaRequest, opts ...grpc.CallOption) (*CreatePizzaResponse, error)
	GetPizzas(ctx context.Context, in *GetPizzasRequest, opts ...grpc.CallOption) (*GetPizzasResponse, error)
	GetPizzaById(ctx context.Context, in *GetPizzaByIdRequest, opts ...grpc.CallOption) (*GetPizzaByIdResponse, error)
	UpdatePizza(ctx context.Context, in *UpdatePizzaRequest, opts ...grpc.CallOption) (*UpdatePizzaResponse, error)
	DeletePizza(ctx context.Context, in *DeletePizzaRequest, opts ...grpc.CallOption) (*DeletePizzaResponse, error)
	GetPizzaCost(ctx context.Context, in *CartItems, opts ...grpc.CallOption) (*CartItemsResp, error)
}

type pizzaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPizzaServiceClient(cc grpc.ClientConnInterface) PizzaServiceClient {
	return &pizzaServiceClient{cc}
}

func (c *pizzaServiceClient) CreatePizza(ctx context.Context, in *CreatePizzaRequest, opts ...grpc.CallOption) (*CreatePizzaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePizzaResponse)
	err := c.cc.Invoke(ctx, PizzaService_CreatePizza_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pizzaServiceClient) CreatePizzaType(ctx context.Context, in *CreatePizzaRequest, opts ...grpc.CallOption) (*CreatePizzaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePizzaResponse)
	err := c.cc.Invoke(ctx, PizzaService_CreatePizzaType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pizzaServiceClient) GetPizzas(ctx context.Context, in *GetPizzasRequest, opts ...grpc.CallOption) (*GetPizzasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPizzasResponse)
	err := c.cc.Invoke(ctx, PizzaService_GetPizzas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pizzaServiceClient) GetPizzaById(ctx context.Context, in *GetPizzaByIdRequest, opts ...grpc.CallOption) (*GetPizzaByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPizzaByIdResponse)
	err := c.cc.Invoke(ctx, PizzaService_GetPizzaById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pizzaServiceClient) UpdatePizza(ctx context.Context, in *UpdatePizzaRequest, opts ...grpc.CallOption) (*UpdatePizzaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePizzaResponse)
	err := c.cc.Invoke(ctx, PizzaService_UpdatePizza_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pizzaServiceClient) DeletePizza(ctx context.Context, in *DeletePizzaRequest, opts ...grpc.CallOption) (*DeletePizzaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePizzaResponse)
	err := c.cc.Invoke(ctx, PizzaService_DeletePizza_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pizzaServiceClient) GetPizzaCost(ctx context.Context, in *CartItems, opts ...grpc.CallOption) (*CartItemsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CartItemsResp)
	err := c.cc.Invoke(ctx, PizzaService_GetPizzaCost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PizzaServiceServer is the server API for PizzaService service.
// All implementations must embed UnimplementedPizzaServiceServer
// for forward compatibility.
type PizzaServiceServer interface {
	CreatePizza(context.Context, *CreatePizzaRequest) (*CreatePizzaResponse, error)
	CreatePizzaType(context.Context, *CreatePizzaRequest) (*CreatePizzaResponse, error)
	GetPizzas(context.Context, *GetPizzasRequest) (*GetPizzasResponse, error)
	GetPizzaById(context.Context, *GetPizzaByIdRequest) (*GetPizzaByIdResponse, error)
	UpdatePizza(context.Context, *UpdatePizzaRequest) (*UpdatePizzaResponse, error)
	DeletePizza(context.Context, *DeletePizzaRequest) (*DeletePizzaResponse, error)
	GetPizzaCost(context.Context, *CartItems) (*CartItemsResp, error)
	mustEmbedUnimplementedPizzaServiceServer()
}

// UnimplementedPizzaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPizzaServiceServer struct{}

func (UnimplementedPizzaServiceServer) CreatePizza(context.Context, *CreatePizzaRequest) (*CreatePizzaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePizza not implemented")
}
func (UnimplementedPizzaServiceServer) CreatePizzaType(context.Context, *CreatePizzaRequest) (*CreatePizzaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePizzaType not implemented")
}
func (UnimplementedPizzaServiceServer) GetPizzas(context.Context, *GetPizzasRequest) (*GetPizzasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPizzas not implemented")
}
func (UnimplementedPizzaServiceServer) GetPizzaById(context.Context, *GetPizzaByIdRequest) (*GetPizzaByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPizzaById not implemented")
}
func (UnimplementedPizzaServiceServer) UpdatePizza(context.Context, *UpdatePizzaRequest) (*UpdatePizzaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePizza not implemented")
}
func (UnimplementedPizzaServiceServer) DeletePizza(context.Context, *DeletePizzaRequest) (*DeletePizzaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePizza not implemented")
}
func (UnimplementedPizzaServiceServer) GetPizzaCost(context.Context, *CartItems) (*CartItemsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPizzaCost not implemented")
}
func (UnimplementedPizzaServiceServer) mustEmbedUnimplementedPizzaServiceServer() {}
func (UnimplementedPizzaServiceServer) testEmbeddedByValue()                      {}

// UnsafePizzaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PizzaServiceServer will
// result in compilation errors.
type UnsafePizzaServiceServer interface {
	mustEmbedUnimplementedPizzaServiceServer()
}

func RegisterPizzaServiceServer(s grpc.ServiceRegistrar, srv PizzaServiceServer) {
	// If the following call pancis, it indicates UnimplementedPizzaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PizzaService_ServiceDesc, srv)
}

func _PizzaService_CreatePizza_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePizzaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PizzaServiceServer).CreatePizza(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PizzaService_CreatePizza_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PizzaServiceServer).CreatePizza(ctx, req.(*CreatePizzaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PizzaService_CreatePizzaType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePizzaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PizzaServiceServer).CreatePizzaType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PizzaService_CreatePizzaType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PizzaServiceServer).CreatePizzaType(ctx, req.(*CreatePizzaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PizzaService_GetPizzas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPizzasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PizzaServiceServer).GetPizzas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PizzaService_GetPizzas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PizzaServiceServer).GetPizzas(ctx, req.(*GetPizzasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PizzaService_GetPizzaById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPizzaByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PizzaServiceServer).GetPizzaById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PizzaService_GetPizzaById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PizzaServiceServer).GetPizzaById(ctx, req.(*GetPizzaByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PizzaService_UpdatePizza_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePizzaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PizzaServiceServer).UpdatePizza(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PizzaService_UpdatePizza_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PizzaServiceServer).UpdatePizza(ctx, req.(*UpdatePizzaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PizzaService_DeletePizza_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePizzaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PizzaServiceServer).DeletePizza(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PizzaService_DeletePizza_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PizzaServiceServer).DeletePizza(ctx, req.(*DeletePizzaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PizzaService_GetPizzaCost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CartItems)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PizzaServiceServer).GetPizzaCost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PizzaService_GetPizzaCost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PizzaServiceServer).GetPizzaCost(ctx, req.(*CartItems))
	}
	return interceptor(ctx, in, info, handler)
}

// PizzaService_ServiceDesc is the grpc.ServiceDesc for PizzaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PizzaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PizzaService",
	HandlerType: (*PizzaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePizza",
			Handler:    _PizzaService_CreatePizza_Handler,
		},
		{
			MethodName: "CreatePizzaType",
			Handler:    _PizzaService_CreatePizzaType_Handler,
		},
		{
			MethodName: "GetPizzas",
			Handler:    _PizzaService_GetPizzas_Handler,
		},
		{
			MethodName: "GetPizzaById",
			Handler:    _PizzaService_GetPizzaById_Handler,
		},
		{
			MethodName: "UpdatePizza",
			Handler:    _PizzaService_UpdatePizza_Handler,
		},
		{
			MethodName: "DeletePizza",
			Handler:    _PizzaService_DeletePizza_Handler,
		},
		{
			MethodName: "GetPizzaCost",
			Handler:    _PizzaService_GetPizzaCost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pizza.proto",
}

const (
	CartService_Cart_FullMethodName                  = "/proto.CartService/Cart"
	CartService_DecreasePizzaQuantity_FullMethodName = "/proto.CartService/DecreasePizzaQuantity"
	CartService_GetTotalCost_FullMethodName          = "/proto.CartService/GetTotalCost"
	CartService_GetCartHistory_FullMethodName        = "/proto.CartService/GetCartHistory"
	CartService_GetCartItemHistory_FullMethodName    = "/proto.CartService/GetCartItemHistory"
	CartService_GetFromCart_FullMethodName           = "/proto.CartService/GetFromCart"
	CartService_ClearTheCart_FullMethodName          = "/proto.CartService/ClearTheCart"
	CartService_ClearTheCartById_FullMethodName      = "/proto.CartService/ClearTheCartById"
)

// CartServiceClient is the client API for CartService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CartServiceClient interface {
	Cart(ctx context.Context, in *CartRequest, opts ...grpc.CallOption) (*CartResponse, error)
	DecreasePizzaQuantity(ctx context.Context, in *CartItems, opts ...grpc.CallOption) (*CartItemsResp, error)
	GetTotalCost(ctx context.Context, in *CartItems, opts ...grpc.CallOption) (*CartItemsResp, error)
	GetCartHistory(ctx context.Context, in *GetCartHistoryRequest, opts ...grpc.CallOption) (*GetCartHistoryResponse, error)
	GetCartItemHistory(ctx context.Context, in *GetCartItemHistoryRequest, opts ...grpc.CallOption) (*GetCartItemHistoryResponse, error)
	GetFromCart(ctx context.Context, in *CartItems, opts ...grpc.CallOption) (*CartItemsResp, error)
	ClearTheCart(ctx context.Context, in *CartItems, opts ...grpc.CallOption) (*CartItemsResp, error)
	ClearTheCartById(ctx context.Context, in *CartItems, opts ...grpc.CallOption) (*CartItemsResp, error)
}

type cartServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCartServiceClient(cc grpc.ClientConnInterface) CartServiceClient {
	return &cartServiceClient{cc}
}

func (c *cartServiceClient) Cart(ctx context.Context, in *CartRequest, opts ...grpc.CallOption) (*CartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CartResponse)
	err := c.cc.Invoke(ctx, CartService_Cart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartServiceClient) DecreasePizzaQuantity(ctx context.Context, in *CartItems, opts ...grpc.CallOption) (*CartItemsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CartItemsResp)
	err := c.cc.Invoke(ctx, CartService_DecreasePizzaQuantity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartServiceClient) GetTotalCost(ctx context.Context, in *CartItems, opts ...grpc.CallOption) (*CartItemsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CartItemsResp)
	err := c.cc.Invoke(ctx, CartService_GetTotalCost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartServiceClient) GetCartHistory(ctx context.Context, in *GetCartHistoryRequest, opts ...grpc.CallOption) (*GetCartHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCartHistoryResponse)
	err := c.cc.Invoke(ctx, CartService_GetCartHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartServiceClient) GetCartItemHistory(ctx context.Context, in *GetCartItemHistoryRequest, opts ...grpc.CallOption) (*GetCartItemHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCartItemHistoryResponse)
	err := c.cc.Invoke(ctx, CartService_GetCartItemHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartServiceClient) GetFromCart(ctx context.Context, in *CartItems, opts ...grpc.CallOption) (*CartItemsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CartItemsResp)
	err := c.cc.Invoke(ctx, CartService_GetFromCart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartServiceClient) ClearTheCart(ctx context.Context, in *CartItems, opts ...grpc.CallOption) (*CartItemsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CartItemsResp)
	err := c.cc.Invoke(ctx, CartService_ClearTheCart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartServiceClient) ClearTheCartById(ctx context.Context, in *CartItems, opts ...grpc.CallOption) (*CartItemsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CartItemsResp)
	err := c.cc.Invoke(ctx, CartService_ClearTheCartById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CartServiceServer is the server API for CartService service.
// All implementations must embed UnimplementedCartServiceServer
// for forward compatibility.
type CartServiceServer interface {
	Cart(context.Context, *CartRequest) (*CartResponse, error)
	DecreasePizzaQuantity(context.Context, *CartItems) (*CartItemsResp, error)
	GetTotalCost(context.Context, *CartItems) (*CartItemsResp, error)
	GetCartHistory(context.Context, *GetCartHistoryRequest) (*GetCartHistoryResponse, error)
	GetCartItemHistory(context.Context, *GetCartItemHistoryRequest) (*GetCartItemHistoryResponse, error)
	GetFromCart(context.Context, *CartItems) (*CartItemsResp, error)
	ClearTheCart(context.Context, *CartItems) (*CartItemsResp, error)
	ClearTheCartById(context.Context, *CartItems) (*CartItemsResp, error)
	mustEmbedUnimplementedCartServiceServer()
}

// UnimplementedCartServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCartServiceServer struct{}

func (UnimplementedCartServiceServer) Cart(context.Context, *CartRequest) (*CartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Cart not implemented")
}
func (UnimplementedCartServiceServer) DecreasePizzaQuantity(context.Context, *CartItems) (*CartItemsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecreasePizzaQuantity not implemented")
}
func (UnimplementedCartServiceServer) GetTotalCost(context.Context, *CartItems) (*CartItemsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTotalCost not implemented")
}
func (UnimplementedCartServiceServer) GetCartHistory(context.Context, *GetCartHistoryRequest) (*GetCartHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCartHistory not implemented")
}
func (UnimplementedCartServiceServer) GetCartItemHistory(context.Context, *GetCartItemHistoryRequest) (*GetCartItemHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCartItemHistory not implemented")
}
func (UnimplementedCartServiceServer) GetFromCart(context.Context, *CartItems) (*CartItemsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFromCart not implemented")
}
func (UnimplementedCartServiceServer) ClearTheCart(context.Context, *CartItems) (*CartItemsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearTheCart not implemented")
}
func (UnimplementedCartServiceServer) ClearTheCartById(context.Context, *CartItems) (*CartItemsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearTheCartById not implemented")
}
func (UnimplementedCartServiceServer) mustEmbedUnimplementedCartServiceServer() {}
func (UnimplementedCartServiceServer) testEmbeddedByValue()                     {}

// UnsafeCartServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CartServiceServer will
// result in compilation errors.
type UnsafeCartServiceServer interface {
	mustEmbedUnimplementedCartServiceServer()
}

func RegisterCartServiceServer(s grpc.ServiceRegistrar, srv CartServiceServer) {
	// If the following call pancis, it indicates UnimplementedCartServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CartService_ServiceDesc, srv)
}

func _CartService_Cart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartServiceServer).Cart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CartService_Cart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartServiceServer).Cart(ctx, req.(*CartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CartService_DecreasePizzaQuantity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CartItems)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartServiceServer).DecreasePizzaQuantity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CartService_DecreasePizzaQuantity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartServiceServer).DecreasePizzaQuantity(ctx, req.(*CartItems))
	}
	return interceptor(ctx, in, info, handler)
}

func _CartService_GetTotalCost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CartItems)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartServiceServer).GetTotalCost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CartService_GetTotalCost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartServiceServer).GetTotalCost(ctx, req.(*CartItems))
	}
	return interceptor(ctx, in, info, handler)
}

func _CartService_GetCartHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCartHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartServiceServer).GetCartHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CartService_GetCartHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartServiceServer).GetCartHistory(ctx, req.(*GetCartHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CartService_GetCartItemHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCartItemHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartServiceServer).GetCartItemHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CartService_GetCartItemHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartServiceServer).GetCartItemHistory(ctx, req.(*GetCartItemHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CartService_GetFromCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CartItems)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartServiceServer).GetFromCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CartService_GetFromCart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartServiceServer).GetFromCart(ctx, req.(*CartItems))
	}
	return interceptor(ctx, in, info, handler)
}

func _CartService_ClearTheCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CartItems)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartServiceServer).ClearTheCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CartService_ClearTheCart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartServiceServer).ClearTheCart(ctx, req.(*CartItems))
	}
	return interceptor(ctx, in, info, handler)
}

func _CartService_ClearTheCartById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CartItems)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartServiceServer).ClearTheCartById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CartService_ClearTheCartById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartServiceServer).ClearTheCartById(ctx, req.(*CartItems))
	}
	return interceptor(ctx, in, info, handler)
}

// CartService_ServiceDesc is the grpc.ServiceDesc for CartService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CartService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CartService",
	HandlerType: (*CartServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Cart",
			Handler:    _CartService_Cart_Handler,
		},
		{
			MethodName: "DecreasePizzaQuantity",
			Handler:    _CartService_DecreasePizzaQuantity_Handler,
		},
		{
			MethodName: "GetTotalCost",
			Handler:    _CartService_GetTotalCost_Handler,
		},
		{
			MethodName: "GetCartHistory",
			Handler:    _CartService_GetCartHistory_Handler,
		},
		{
			MethodName: "GetCartItemHistory",
			Handler:    _CartService_GetCartItemHistory_Handler,
		},
		{
			MethodName: "GetFromCart",
			Handler:    _CartService_GetFromCart_Handler,
		},
		{
			MethodName: "ClearTheCart",
			Handler:    _CartService_ClearTheCart_Handler,
		},
		{
			MethodName: "ClearTheCartById",
			Handler:    _CartService_ClearTheCartById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pizza.proto",
}

const (
	OrderService_CheckIsOrdered_FullMethodName = "/proto.OrderService/CheckIsOrdered"
	OrderService_OrderPizza_FullMethodName     = "/proto.OrderService/OrderPizza"
)

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderServiceClient interface {
	CheckIsOrdered(ctx context.Context, in *CheckIsOrderedRequest, opts ...grpc.CallOption) (*CheckIsOrderedResponse, error)
	OrderPizza(ctx context.Context, in *OrderPizzaRequest, opts ...grpc.CallOption) (*OrderPizzaResponse, error)
}

type orderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderServiceClient(cc grpc.ClientConnInterface) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) CheckIsOrdered(ctx context.Context, in *CheckIsOrderedRequest, opts ...grpc.CallOption) (*CheckIsOrderedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckIsOrderedResponse)
	err := c.cc.Invoke(ctx, OrderService_CheckIsOrdered_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) OrderPizza(ctx context.Context, in *OrderPizzaRequest, opts ...grpc.CallOption) (*OrderPizzaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderPizzaResponse)
	err := c.cc.Invoke(ctx, OrderService_OrderPizza_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceServer is the server API for OrderService service.
// All implementations must embed UnimplementedOrderServiceServer
// for forward compatibility.
type OrderServiceServer interface {
	CheckIsOrdered(context.Context, *CheckIsOrderedRequest) (*CheckIsOrderedResponse, error)
	OrderPizza(context.Context, *OrderPizzaRequest) (*OrderPizzaResponse, error)
	mustEmbedUnimplementedOrderServiceServer()
}

// UnimplementedOrderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderServiceServer struct{}

func (UnimplementedOrderServiceServer) CheckIsOrdered(context.Context, *CheckIsOrderedRequest) (*CheckIsOrderedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckIsOrdered not implemented")
}
func (UnimplementedOrderServiceServer) OrderPizza(context.Context, *OrderPizzaRequest) (*OrderPizzaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderPizza not implemented")
}
func (UnimplementedOrderServiceServer) mustEmbedUnimplementedOrderServiceServer() {}
func (UnimplementedOrderServiceServer) testEmbeddedByValue()                      {}

// UnsafeOrderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderServiceServer will
// result in compilation errors.
type UnsafeOrderServiceServer interface {
	mustEmbedUnimplementedOrderServiceServer()
}

func RegisterOrderServiceServer(s grpc.ServiceRegistrar, srv OrderServiceServer) {
	// If the following call pancis, it indicates UnimplementedOrderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderService_ServiceDesc, srv)
}

func _OrderService_CheckIsOrdered_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckIsOrderedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).CheckIsOrdered(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_CheckIsOrdered_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).CheckIsOrdered(ctx, req.(*CheckIsOrderedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_OrderPizza_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderPizzaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).OrderPizza(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_OrderPizza_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).OrderPizza(ctx, req.(*OrderPizzaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderService_ServiceDesc is the grpc.ServiceDesc for OrderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckIsOrdered",
			Handler:    _OrderService_CheckIsOrdered_Handler,
		},
		{
			MethodName: "OrderPizza",
			Handler:    _OrderService_OrderPizza_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pizza.proto",
}
