DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS pizza;
DROP TABLE IF EXISTS pizza_types;
DROP TABLE IF EXISTS order;
DROP TABLE IF EXISTS order_item;
DROP TABLE IF EXISTS cart;
DROP TABLE IF EXISTS cart_item;
DROP TABLE IF EXISTS session;
